const Recipe = require("../../models/user/Recipe");
const MealPlan = require("../../models/MealPlan");

// GET AI feature status + usage stats
const getAIStatus = async (req, res) => {
  try {
    const [aiRecipes, manualRecipes, totalMealPlans] = await Promise.all([
      Recipe.countDocuments({ source: "ai" }),
      Recipe.countDocuments({ source: { $ne: "ai" } }),
      MealPlan.countDocuments(),
    ]);

    res.status(200).json({
      success: true,
      status: {
        configured: Boolean(process.env.GEMINI_API_KEY),
        model: "gemini-3.6-flash",
        aiRecipes,
        manualRecipes,
        // Every meal plan in MealMate is generated by the AI meal planner
        aiMealPlans: totalMealPlans,
      },
    });
  } catch (error) {
    console.error(error);
    res.status(500).json({ success: false, message: "Failed to get AI status" });
  }
};

module.exports = { getAIStatus };
