import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import {
  ArrowLeft,
  TrendingUp,
  Users,
  ChefHat,
  ClipboardList,
  ShoppingBasket,
  UserPlus,
} from "lucide-react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts";

export default function Analytics() {
  const [, setLocation] = useLocation();

  const [stats, setStats] = useState(null);
  const [recentUsers, setRecentUsers] = useState([]);
  const [recentMealPlans, setRecentMealPlans] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchStats();
  }, []);

  const fetchStats = async () => {
    try {
      const token = localStorage.getItem("token");

      if (!token) {
        setLocation("/login");
        return;
      }

      const response = await fetch("http://localhost:5000/api/admin/analytics/stats", {
        headers: { Authorization: `Bearer ${token}` },
      });

      const data = await response.json();

      if (!response.ok) {
        alert(data.message || "Failed to load analytics");
        return;
      }

      setStats(data.stats);
      setRecentUsers(data.recentUsers || []);
      setRecentMealPlans(data.recentMealPlans || []);
    } catch (error) {
      console.error(error);
      alert("Unable to connect to server.");
    } finally {
      setLoading(false);
    }
  };

  const chartData = stats
    ? [
        { name: "Users", value: stats.totalUsers },
        { name: "Recipes", value: stats.totalRecipes },
        { name: "Meal Plans", value: stats.totalMealPlans },
        { name: "Grocery Lists", value: stats.totalGroceryLists },
      ]
    : [];

  return (
    <div className="min-h-screen bg-[#f7faf7]">
      <header className="sticky top-0 z-30 bg-white/95 backdrop-blur border-b border-gray-100">
        <div className="max-w-6xl mx-auto h-20 px-4 sm:px-6 lg:px-8 flex items-center gap-4">
          <button
            onClick={() => setLocation("/dashboard")}
            className="w-10 h-10 rounded-xl border border-gray-200 flex items-center justify-center hover:bg-gray-50 transition"
          >
            <ArrowLeft className="w-5 h-5 text-gray-700" />
          </button>

          <div className="flex items-center gap-3">
            <div className="w-11 h-11 rounded-xl bg-green-50 flex items-center justify-center">
              <TrendingUp className="w-6 h-6 text-primary" />
            </div>
            <div>
              <h1 className="text-xl font-black text-gray-900">Analytics</h1>
              <p className="text-xs text-gray-400">Platform-wide usage overview</p>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
        {loading || !stats ? (
          <p className="text-gray-400">Loading analytics...</p>
        ) : (
          <>
            <section className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
              <StatCard
                icon={<Users className="w-6 h-6 text-primary" />}
                label="Total Users"
                value={stats.totalUsers}
                description={`${stats.totalAdmins} admin${stats.totalAdmins === 1 ? "" : "s"}`}
              />
              <StatCard
                icon={<ChefHat className="w-6 h-6 text-primary" />}
                label="Recipes"
                value={stats.totalRecipes}
                description="Available on the platform"
              />
              <StatCard
                icon={<ClipboardList className="w-6 h-6 text-primary" />}
                label="Meal Plans"
                value={stats.totalMealPlans}
                description="Created by users"
              />
              <StatCard
                icon={<ShoppingBasket className="w-6 h-6 text-primary" />}
                label="Grocery Lists"
                value={stats.totalGroceryLists}
                description="Generated by users"
              />
            </section>

            <section className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6 md:p-8">
              <h2 className="text-lg font-black text-gray-900 mb-6">Platform Overview</h2>

              <div className="h-72">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={chartData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
                    <XAxis dataKey="name" tick={{ fontSize: 12, fill: "#6b7280" }} />
                    <YAxis allowDecimals={false} tick={{ fontSize: 12, fill: "#6b7280" }} />
                    <Tooltip />
                    <Bar dataKey="value" fill="#22c55e" radius={[6, 6, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </section>

            <section className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6">
                <h2 className="text-base font-black text-gray-900 mb-4">Recently Joined</h2>

                {recentUsers.length === 0 ? (
                  <p className="text-sm text-gray-400">No users yet.</p>
                ) : (
                  <div className="space-y-3">
                    {recentUsers.map((u) => (
                      <div key={u._id} className="flex items-center gap-3 p-3 rounded-xl bg-gray-50">
                        <div className="w-9 h-9 rounded-lg bg-white flex items-center justify-center shrink-0">
                          <UserPlus className="w-4 h-4 text-primary" />
                        </div>
                        <div className="min-w-0">
                          <p className="text-sm font-semibold text-gray-800 truncate">{u.name}</p>
                          <p className="text-xs text-gray-400 truncate">{u.email}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6">
                <h2 className="text-base font-black text-gray-900 mb-4">Latest Meal Plans</h2>

                {recentMealPlans.length === 0 ? (
                  <p className="text-sm text-gray-400">No meal plans yet.</p>
                ) : (
                  <div className="space-y-3">
                    {recentMealPlans.map((plan) => (
                      <div key={plan._id} className="flex items-center gap-3 p-3 rounded-xl bg-gray-50">
                        <div className="w-9 h-9 rounded-lg bg-white flex items-center justify-center shrink-0">
                          <ClipboardList className="w-4 h-4 text-primary" />
                        </div>
                        <div className="min-w-0">
                          <p className="text-sm font-semibold text-gray-800 truncate">
                            {plan.user?.name || "Unknown user"} · {plan.goal}
                          </p>
                          <p className="text-xs text-gray-400 truncate">
                            {plan.duration} days · {plan.diet}
                          </p>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </section>
          </>
        )}
      </main>
    </div>
  );
}

function StatCard({ icon, label, value, description }) {
  return (
    <div className="bg-white rounded-2xl border border-gray-100 p-6 shadow-sm hover:shadow-md transition-all">
      <div className="flex items-start justify-between">
        <div>
          <p className="text-sm text-gray-500">{label}</p>
          <p className="text-3xl font-black text-gray-900 mt-2">{value}</p>
          <p className="text-xs text-gray-400 mt-2">{description}</p>
        </div>
        <div className="w-11 h-11 rounded-xl bg-green-50 flex items-center justify-center">
          {icon}
        </div>
      </div>
    </div>
  );
}
